baseURL = "https://senyosimpson.com"
languageCode = "en-us"
title = "Bloom 🌹"
theme = "kiss"
googleAnalytics = ""
Paginate = 10 # Number of posts per page
publishdir = "site"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"

[params.info]
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Bloom" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = false # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.social]
twitter = "SenYeezus"
github = "senyosimpson"
email = "simpsonsenyo@gmail.com"
linkedin = "senyo-simpson-997951157"

[params.social.config]
platforms = ["twitter", "github", "linkedin", "email"]

[taxonomies]
tag = "tags"

[params.sections_left]
"/about" = "About"
"/essays" = "Essays"
"/philosophy" = "Core Philosophy"

[markup]
  [markup.highlight]
      style = "manni"
