baseURL = "https://senyosimpson.com"
languageCode = "en-us"
title = "Bloom 🌹"
theme = "kiss"
googleAnalytics = ""
Paginate = 10 # Number of posts per page
publishdir = "site"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"

[params.info]
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Bloom" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = false # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.social]
twitter = "SenYeezus"
github = "senyosimpson"
email = "simpsonsenyo@gmail.com"
linkedin = "senyo-simpson-997951157"

[params.social.config]
platforms = ["twitter", "github", "linkedin", "email"]

[taxonomies]
tag = "tags"

  [params.sections_left.bakery]
    path = "/short-forms"
    name = "Short Forms"
    rank = 1

  [params.sections_left.essays]
    path = "/essays"
    name = "Essays"
    rank = 2

  [params.sections_left.talks]
    path = "/talks"
    name = "Talks"
    rank = 3

  [params.sections_left.philosophy]
    path = "/philosophy"
    name = "Core Philosophy"
    rank = 4

  [params.sections_left]
    [params.sections_left.about]
      path = "/about"
      name = "About"
      rank = 5

[markup]
  [markup.highlight]
      style = "manni"
