baseURL = "http://senyosimpson.github.io/"
languageCode = "en-us"
title = "Bloom"
theme = "ananke"
publishdir = "../"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[params]
  favicon = ""
  description = "A Tale of Growth"
  twitter = "https://twitter.com/senyo_simpson"
  github = ""
  linkedin = "https://www.linkedin.com/in/senyo-simpson-997951157/"
  
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/prologue-and-promise.jpg"
  recent_posts_number = 2