---
- hosts: digitalocean
  remote_user: root
  become: true

  tasks:
    - name: Transfer blog to remote
      ansible.posix.synchronize:
        src: /media/senyo/senYeezus/Senyo/blog/
        dest: /home/senyo/blog/
        delete: yes
        rsync_opts:
          - "--exclude=.git"

    - name: Start docker compose
      shell:
        cmd: docker-compose up -d --force-recreate blog
        chdir: /home/senyo/blog/infra/docker-compose

    - name: Docker prune
      docker_prune:
        images: yes
        containers: yes
        networks: yes
